// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace CSharpPredictorML.Model
{
    public class ModelInput
    {
        [ColumnName("Company"), LoadColumn(0)]
        public string Company { get; set; }


        [ColumnName("Model"), LoadColumn(1)]
        public string Model { get; set; }


        [ColumnName("Mileage"), LoadColumn(2)]
        public float Mileage { get; set; }


        [ColumnName("EnginePower"), LoadColumn(3)]
        public float EnginePower { get; set; }


        [ColumnName("EngineVolume"), LoadColumn(4)]
        public float EngineVolume { get; set; }


        [ColumnName("Year"), LoadColumn(5)]
        public float Year { get; set; }


        [ColumnName("Transmission"), LoadColumn(6)]
        public bool Transmission { get; set; }


        [ColumnName("Link"), LoadColumn(7)]
        public string Link { get; set; }


        [ColumnName("Price"), LoadColumn(8)]
        public float Price { get; set; }


    }
}
